version: '3.7'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345abcde
    ports:
      - '3306:3306'

  server:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    command:
      - /bin/bash
      - -c
      - |
        cd /backend
        /wait-for-it.sh db:3306 -- java -jar build/libs/backend-0.0.1-SNAPSHOT.jar

  web:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - server
